set(_CATKIN_CURRENT_PACKAGE "KalmanFilter")
set(KalmanFilter_VERSION "0.0.0")
set(KalmanFilter_MAINTAINER "li <li@todo.todo>")
set(KalmanFilter_PACKAGE_FORMAT "2")
set(KalmanFilter_BUILD_DEPENDS "roscpp" "rospy")
set(KalmanFilter_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(KalmanFilter_BUILDTOOL_DEPENDS "catkin")
set(KalmanFilter_BUILDTOOL_EXPORT_DEPENDS )
set(KalmanFilter_EXEC_DEPENDS "roscpp" "rospy")
set(KalmanFilter_RUN_DEPENDS "roscpp" "rospy")
set(KalmanFilter_TEST_DEPENDS )
set(KalmanFilter_DOC_DEPENDS )
set(KalmanFilter_URL_WEBSITE "")
set(KalmanFilter_URL_BUGTRACKER "")
set(KalmanFilter_URL_REPOSITORY "")
set(KalmanFilter_DEPRECATED "")